v = vim.o
v.splitright = true
v.nu = true
v.relativenumber = true
v.tabstop = 4
v.softtabstop = 4
v.shiftwidth = 4
v.expandtab = true
v.smartindent = true
v.wrap = false
v.swapfile = false
v.backup = false
v.undodir = os.getenv("HOME") .. "/.vim/undodir"
v.undofile = true
v.hlsearch = false
v.incsearch = true
v.termguicolors = true
v.scrolloff = 8
v.signcolumn = "yes"
v.updatetime = 50
v.colorcolumn = "80"
vim.g.mapleader = " "
